name: sistema_movil_inventariado
description: Sistema de inventario profesional para municipalidad

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

# Configuración del icono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "lib/assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
